import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // CarboNudge — Eco-Systemic Precision design tokens
        "surface-tint": "#3b6934",
        "text-heading": "#0F172A",
        "on-secondary-fixed": "#131f00",
        "secondary-fixed": "#c2f366",
        "on-secondary-fixed-variant": "#364e00",
        "on-error": "#ffffff",
        "surface-variant": "#d5e3fd",
        secondary: "#496800",
        "primary-container": "#2d5a27",
        "on-surface": "#0d1c2f",
        "primary-fixed-dim": "#a1d494",
        "primary-fixed": "#bcf0ae",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed-variant": "#004c69",
        "on-background": "#0d1c2f",
        "tertiary-container": "#005676",
        "surface-white": "#FFFFFF",
        outline: "#72796e",
        "chart-atmospheric": "#38BDF8",
        "inverse-surface": "#233144",
        "surface-dim": "#ccdbf4",
        "surface-container": "#e6eeff",
        tertiary: "#003e56",
        "tertiary-fixed": "#c4e7ff",
        "surface-container-high": "#dde9ff",
        "on-primary-fixed": "#002201",
        "secondary-fixed-dim": "#a6d64d",
        error: "#ba1a1a",
        "inverse-on-surface": "#ebf1ff",
        "on-error-container": "#93000a",
        "on-primary-container": "#9dd090",
        "surface-container-low": "#eff4ff",
        primary: "#154212",
        "on-tertiary-fixed": "#001e2c",
        "outline-variant": "#c2c9bb",
        "error-container": "#ffdad6",
        "secondary-container": "#c2f366",
        "on-primary": "#ffffff",
        "on-secondary": "#ffffff",
        "surface-container-highest": "#d5e3fd",
        background: "#f8f9ff",
        "on-tertiary-container": "#6ecdff",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed-dim": "#7bd0ff",
        "background-subtle": "#F8FAFC",
        "on-secondary-container": "#4d6e00",
        "chart-growth": "#A2D149",
        "on-surface-variant": "#42493e",
        "surface-bright": "#f8f9ff",
        surface: "#f8f9ff",
        "on-primary-fixed-variant": "#23501e",
        "inverse-primary": "#a1d494",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      spacing: {
        gutter: "24px",
        "margin-desktop": "64px",
        "margin-mobile": "16px",
        base: "4px",
        "container-max": "1280px",
      },
      fontFamily: {
        "headline-lg-mobile": ["Hanken Grotesk", "sans-serif"],
        "label-sm": ["JetBrains Mono", "monospace"],
        "label-xs": ["JetBrains Mono", "monospace"],
        "headline-md": ["Hanken Grotesk", "sans-serif"],
        "display-lg": ["Hanken Grotesk", "sans-serif"],
        "headline-lg": ["Hanken Grotesk", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        sans: ["Inter", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-xs": ["10px", { lineHeight: "14px", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
      },
    },
  },
  plugins: [require("@tailwindcss/typography"), require("@tailwindcss/forms")],
};
export default config;